### ISSUE TITLE
robot deploy accumulates  cron jobs, eventually causing errors

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/web-archiving#1]
cron jobs seem to point to specific release directory, not "current" so can end up with multiple cron jobs for same robot, and/or cron jobs for specific release directories that no longer exist

**Comment by drh-stanford** [comment]
The `whenever` gem uses the specific release directory rather than the `current` symlink. It will replace the cron jobs on a new deploy, _but_ if the app or stage name changes it will cause duplicates. For example, it keys off of `"was-crawl-preassembly_staging"` to replace the cron jobs, so if that key changes, you'll get duplicates.

```
# Begin Whenever generated tasks for: was-crawl-preassembly_staging
0,5,10,15,20,25,30,35,40,45,50,55 * * * * /bin/bash -l -c 'cd /home/lyberadmin/was-crawl-preassembly/releases/20160621225331 && ROBOT_ENVIRONMENT=test bundle exec rake robots:verify --silent > log/verify.log 2> log/cron.log'

# End Whenever generated tasks for: was-crawl-preassembly_staging
```

**Comment by ndushay** [comment]
so the issue may have been that the app or stage name changed and so an old cron was kept there because of that?    Seems plausible -- I may have noticed "test" vs "staging" somewhere.
