### ISSUE TITLE
Do we need the app/ folders in stacks/ and stage/?

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/web-archiving#21]
There's code in there but not clear whether it's used or how it was installed.

**Comment by ndushay** [comment]
I renamed the stacks/app folder to `app-to-be-deleted` because it contained what appeared to be code we now deploy via jenkins, puppet and cap, and no file was more recent than 2 years old.

The `stage/app` folders (stage2 also) appear to be more recent (only 1 year old)  and appear to be scripts pertaining to crawl  manipulations for different origins.

**Comment by ndushay** [comment]
I'm gonna call this question answered.
