### ISSUE TITLE
argo deployment

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/web-archiving#42]
- get approval from BeLyn
- tag
- deploy

**Comment by blalbrit** [comment]
For "get approval" - please: put code on -stage and provide us with a testing rubric for the changes you're making. One or three of us will do further tests on -stage and then give approval.

Please notify the Argo channel on Slack when deploying to -stage or -prod.

**Comment by LynnMcRae** [comment]
A proxy ticket for what ticket, that is, where are the changes described?

**Comment by LynnMcRae** [comment]
or is this just John et al closing out the last of their previous work?

**Comment by jmartin-sul** [comment]
this is just closing out the previous work -- i believe that the big thing here is the move of bulk reindexing from the old bulk updates tool to the new bulk actions tool, though there were some other PRs too.  i think everything was tested individually (on stage where appropriate) before being merged to master.

here's the list of what's been merged to master since v3.13.0 was tagged and deployed, with testing advice for each change:
* fix up permission checking and unit testing for blue buttons on object detail page (sul-dlss/argo#973)
  * check for "Edit APO" and "Create Collection" buttons based on object type instead of presence of roleMetadata datastream.
    * _test_: confirm that buttons display when expected, and are hidden when object type is wrong or user doesn't have permission.
  * buttons that we know are disabled without having to ask another service (e.g. workflow service) are marked disabled via a flag, instead of providing a URL to hit for the check.
    * _test_: confirm in the browser debugger that loading an object detail page with a disabled "Purge" button doesn't result in a 404 among the AJAX calls that the browser makes.  confirm that the "Close Version" and "Open Version" buttons are enabled as expected.
  * disable "Refresh descMetadata" button for objects that aren't open for modification.
    * _test_: confirm that button is enabled/disabled as expected.
  * "Open Version" and "Close Version" buttons should not display at all if user doesn't have permission to open or close the item.
    * _test_: confirm that buttons display (possibly disabled) if user has permission, and that they don't display at all if the user doesn't have permission.
  * slight refactor of the perm check for the "Update Embargo" button
    * _test_: make sure "Update Embargo" still displays as expected for users that can manage the object (and not at all for users that can't).
* don't publish to releaseboard (sul-dlss/argo#975)
  * _test_: make sure argo is still deployable
* centralize logging for bulk actions and argo side of modsulator (desc metadata upload). (sul-dlss/argo#978, sul-dlss/argo#982)
  * _test_: make sure desc metadata upload and bulk actions still work, and that info about their progress gets logged (bulk actions are desc metadata download, release object, reindex, set governing APO).
  * _test_: if job gets reset, make sure success/failure counts are reset, but log is appended to (not sure how to force a failure?)
* move multiple object reindexing from old bulk updates page to new bulk actions page (sul-dlss/argo#980)
  * _test_: make sure command is gone from old page, make sure new bulk action works
* updates to development documentation and developer installation rake task (sul-dlss/argo#976, sul-dlss/argo#979)
  * _test_: make sure argo is still installable on a dev laptop per the instructions in README.md

like i said, i believe this has all been tested on stage individually as the PRs have been merged, and these changes should all be orthogonal to one another, but that's the list, if you're inclined to do any re-testing.  i just deployed all this to stage about an hour ago, so this should all be available there for testing.

https://github.com/sul-dlss/argo/compare/v3.13.0...master
https://github.com/sul-dlss/argo/pull/973
https://github.com/sul-dlss/argo/pull/975
https://github.com/sul-dlss/argo/pull/976
https://github.com/sul-dlss/argo/pull/978
https://github.com/sul-dlss/argo/pull/979
https://github.com/sul-dlss/argo/pull/980
https://github.com/sul-dlss/argo/pull/982

**Comment by jmartin-sul** [comment]
slight correction:  i'm not sure the logging stuff was ever tested on stage.  i think all the other user facing changes got tested, though.

**Comment by jmartin-sul** [comment]
this has been deployed:  https://github.com/sul-dlss/argo/releases/tag/v3.14.0

i had to read the semver guide to have it talk me out of tagging the release as `3.14.159`.  apparently you must zero the patch release if you increment the minor release (because semver is no fun and doesn't appreciate pi jokes).

**Comment by blalbrit** [comment]
lol - at least the issue number, 42, was the correct answer.
