### ISSUE TITLE
add missing nagios checks for was robots

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/web-archiving#5]
Nagios doesn't seem to have checks for all 5 WAS robots (prod).

**Comment by drh-stanford** [comment]
@rsmith11 @tallenaz we're planning to reorganize the Web Archiving robots in production and test, so that the Capistrano deploy uses a single github repo, rather than 5 github repos.

The new organization will be a single application called `was_robot_suite` installed on sul-robots5-test and sul-robots3-prod.

The Nagios check will be for `~lyberadmin/was_robot_suite/current/log/verify.log`. You can see this in action on `sul-robots5-test` currently.

Here is a link to the new github repo: https://github.com/sul-dlss/was_robot_suite

It replaces `was-crawl-preassembly`, `was-crawl-dissemination`, `was-dissemination`, `was-seed-preassembly`, and `was-seed-dissemination`.

**Comment by drh-stanford** [comment]
@ndushay is going to talk to devops to disable the current nagios alerts in prod so we can turn them all off and deploy the new `was_robot_suite`...

**Comment by ndushay** [comment]
current robots nagios notifications turned off.  Will file SAR ticket about new checks needed and old checks that can be removed for prod and stage.

https://newcaprica.stanford.edu/nagios/

**Comment by ndushay** [comment]
blocked by sul-dlss/was_robot_suite#8

**Comment by drh-stanford** [comment]
this is ready now

**Comment by ndushay** [comment]
filed SAR-3194

**Comment by ndushay** [comment]
@kamchan did SAR-3194 so this is finished.
